# General settings that will be available in templates.
site:
    base_url: http://calisthenics.github.io
    disqus_shortname: null
    author: calisthenics.github.io
    brand: calisthenics.github.io


# Settings that affect collections in the document index. Top-level keys of
# collections can be used as document attributes for grouping it in the
# corresponding collecion.
collections:
    tags:
        path: tags
        template: index.html


# Content specific settings, at the moment only templates are specified.
content:
    index:
        template: index.html # default template used for collections
    doc:
        template: page.html
    rss:
        template: rss2.xml
